### ISSUE TITLE
Lightning segmentation missing visualisation

### ISSUE THREAD

**Issue by wizofe** [PhoenixDL/rising#108]
Hi and thanks for the great module! I went through your segmentation example and that's very useful for my project. Unfortunately, you don't show how one can visualise the predictions of the network (i.e. show examples of the network predict to the test/validation dataset using the ground truth and the images). 

Let me know if I just missed that! :)

**Comment by justusschock** [comment]
Hi, you're right, this is not included since this lib does not focus on visualisation, but on efficient augmentation. However, there are various ways to visualise 3d data. The easiest would probably be to plot the examples slice by slice in your tensor board logger with `self.logger.experiment.add_image` inside your training/validation step
