### ISSUE TITLE
[Bug] Compose doesn't forward pytorch functions to internal transforms

### ISSUE THREAD

**Issue by mibaumgartner** [PhoenixDL/rising#27]
**Description**
`Compose` uses a `list` to store the transformation which leads to some problems when specific functions of `torch.nn.Module` should also be applied to children (e.g. the `to()` method).

Quick fix: change `list` to `torch.nn.ModuleList` which limits our transformation to `rising` transforms which are subclasses of `torch.nn.Module`

Other solutions: look at which functions we really need and overwrite them appropriately (should at least fix problems with `to()`)

Status: looking for a better solution because that is not really satisfying... 
Any ideas @justusschock @haarburger ?

**Comment by justusschock** [comment]
We should for sure switch to module list, since otherwise internal states are also not registered as buffers/parameters if necessary. 

I would suggest the following: 
1.) Switch to module list
2.) Wrap all non-module transforms

Alternatively, we could make our own list, which should be a subclass of nn.modulelist, which checks for the `to` attribute (and maybe some others)
