### ISSUE TITLE
[FeatureRequest] Add Equivalent to Models Genesis Transform

### ISSUE THREAD

**Issue by justusschock** [PhoenixDL/rising#98]
add equivalent to transforms described in models genesis https://arxiv.org/abs/1908.06912

**Comment by weningerleon** [comment]
Hi,
I started working on a rising implementation of the genesis transforms. Basically, there are three transforms, (1) local-shuffling, (2) in/outpainting, and (3) non-linear bezier transform. 
(1) and (2) should be straightforward to implement, I should be able to do this next week.
However, (3) is difficult, because pyTorch doesn't yet support unstructured interpolation. Could be that it will be implemented in a future version, 3rd party implementations are already available: https://github.com/pytorch/pytorch/issues/1552

For the moment, I'm using the interpolation function in numpy (https://github.com/PhoenixDL/rising/compare/master...weningerleon:master). Of course, it is not possible to do the augmentation on the GPU in this way. 
What do you think, should we just wait until a pytorch interpolation function is available? Any other suggestions? It wouldn't be ideal if an external dependency would be required for rising....

**Comment by justusschock** [comment]
Theoretically you could look, whether Google Jax offers the functions you need. You could then execute it in GPU and change the results to a torch tensor via dnnpack format without memory copy. But in general I think, we can either depend on some external lib or implement it ourselves.
